### ISSUE TITLE
Hardcoded values in the script

### ISSUE THREAD

**Issue by sp8va100** [ipeter50/ken-burns-effect#6]
Hi, sorry for bothering you again.

As you answered in my previous issue, there are some hardcoded values inside your script.
I have tried using your `kbe.py` to demo random pictures on the Internet, and they seem fine without changing any parameters, so it came to me a question.
In `utils/pipeline.py` line 26 and 27, you set objcommon's focal and baseline to be 512 and 120 for demo and these match the setting of DIML-outdoor dataset, so I guess you were demoing that dataset. 

However, if I want to demo some pictures in other datasets, or the images I took, is it a must to know the focal length and baseline of the camera used to take the images?

Thanks for your helping!

**Comment by pierlj** [comment]
Hi,

In theory, you should use the actual camera parameters instead of 512 and 120. Yet, in practice these values are working correctly even with different cameras. The video examples included in the README were mostly made with pictures taken with a smartphone which did not have a focal of 120mm. 

Changing the focal length will only soften or strengthen the magnitude of the movement. Setting the same focal length as the camera will reproduce movement just as you were filming the same scene and doing the motion manually. Using a different focal, will produce a video of the scene as if everything was bigger or smaller. If you scale all distances of a scene by two and increase the focal by the same factor, you will get the same exact results (see in my thesis, there are more detail examples about this in section 2.2). 

As for the baseline, the authors of the original paper should not have named this parameter like this as it does not correspond to the actual baseline (i.e. the distance between the two cameras), it's a bit misleading. Just keep it fixed and play with the focal.

**Comment by sp8va100** [comment]
Thanks for your reply!

By the way, I met a problem during training. I used DIML-indoor dataset and NYUv2 dataset for training, the image size of the two dataset is different and in code you keep every image's aspect ration and resize the images to maximum dimension = 1024, so it always occurred `RuntimeError: stack expects each tensor to be equal size` in `data_loader.py`. 
For solving this problem, I added centercrop in `data_loader.py` line 34 ~ 43 to crop the images into the same size. But in the end, the training result is not that good. Can you give me some hints about how you deal with the different size of the images in the two dataset?

**Comment by pierlj** [comment]
This is probably because cropping virtually changes the parameters of the camera. This make the training harder as there is no depth consistency between images. One could argue that this should act as a regularization and instead make the network stronger though. 

I am sorry but it's been more than a year since I did not use this repo and I don't have the access anymore to my workspace. I don't remember how I did the merge between the two dataset. 

I recommend that you switch to another depth dataset, the one released by the original author, it is a mix of synthetic scenes and NYUv2 if I recall correctly, it should be larger and have better quality depth maps.

**Comment by sp8va100** [comment]
I took a look of the original author's dataset. Every image in his dataset has a meta data. The meta datas will provide the parameter of field of view which the original author said that it can derive the focal length(https://github.com/sniklaus/3d-ken-burns/issues/39). 
So does it mean that I can not fix the focal length during setting the dataset in `train.py` anymore since every image may have different focal length and I should calculate the focal length depending on the image's meta data in `data_loader.py`? Sorry to ask you about the focal length's problem again.

**Comment by pierlj** [comment]
Yes modifying `data_loader.py` and adding camera parameters for each image would be a good idea to work with multiple datasets.

**Comment by sp8va100** [comment]
Got it! thanks for your helping!
